### ISSUE TITLE
numeric  opertations

### ISSUE THREAD

**Issue by at15** [at15/scala-linter#5]
- [x] divide by one (type 2, always return same)
- [x] mod by one (type 2, always return 0)
- [x] divide by zero(type 3, throw exception)
- [x] mod by zero(type 3, throw exception)

**Comment by mingo-x** [comment]
isn't it solved...?

**Comment by at15** [comment]
@mingo-x I mean add these checks to this linter, not the problem that div by one is not checked :). And  I guess the numeric operation part is finished, except better warning and split into separated file, which is in `enhance` milestone.

**Comment by at15** [comment]
but I am using `receiver.tpe <:< definitions.IntClass.tpe` (which is copied from the example code in http://www.scala-lang.org/old/node/140), does it means `val x = 2.0; x / 0` won't be detected?

**Comment by mingo-x** [comment]
dizzy =.=
